"""Filesystem storage helpers.

Videos and generated artefacts live on disk (per the plan: only paths + summary
stats go in Mongo). Layout::

    storage/exams/<exam_id>/original<ext>
    storage/exams/<exam_id>/clips/event_XXX_<type>_<person>.mp4
    storage/exams/<exam_id>/motion_heatmap.png
"""
from __future__ import annotations

from pathlib import Path

from fastapi import UploadFile

from ..config import settings

_CHUNK = 1024 * 1024  # 1 MiB


def exam_dir(exam_id: str) -> Path:
    d = settings.storage_dir / "exams" / exam_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def clips_dir(exam_id: str) -> Path:
    return exam_dir(exam_id) / "clips"


def video_path(exam_id: str, suffix: str) -> Path:
    return exam_dir(exam_id) / f"original{suffix}"


def heatmap_path(exam_id: str) -> Path:
    return exam_dir(exam_id) / "motion_heatmap.png"


def clip_path(exam_id: str, filename: str) -> Path:
    # ``filename`` is generated by the pipeline; guard against traversal.
    safe = Path(filename).name
    return clips_dir(exam_id) / safe


async def save_upload(upload: UploadFile, dest: Path) -> int:
    """Stream an uploaded file to ``dest`` in chunks. Returns bytes written."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    with open(dest, "wb") as f:
        while True:
            chunk = await upload.read(_CHUNK)
            if not chunk:
                break
            f.write(chunk)
            written += len(chunk)
    await upload.close()
    return written
